version: '3.8'
services:
  app:
    image: node:18
    volumes:
      - ..:/workspace:cached
    working_dir: /workspace
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    command: sleep infinity # Codespaces/VS Code will run your scripts as needed

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
